version: '3'

services:
  customer:
    image: customer:0.1
    container_name: customer
    build:
      context: .
      dockerfile: ./docker/Dockerfile.customer
    ports:
      - "8081:8080"
  token:
    image: token:0.1
    container_name: token
    build:
      context: .
      dockerfile: ./docker/Dockerfile.token
    ports:
      - "8082:8080"